version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    entrypoint: /bin/sh -c "composer install && composer dump-autoload && npm install && npm run build-dev && dockerize -wait tcp://db:3306 -timeout 120s && php bootstrap/migrate.php && php scripts/createAdmin.php && apache2-foreground"
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - .:/var/www/desafio
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
